### ISSUE TITLE
Radio Channel support (satelite)

### ISSUE THREAD

**Issue by x23piracy** [joethefox/Unofficial-Official-XBMC-Remote#58]
Hi,

could you please add satelite radio channel support in the kodi remote app? I can see all the TV Channels and their tags but the radio channels are missing.

It's very comfortable to remotely start a radio channel without the need to turn the tv on.

Regards X23

**Comment by joethefox** [comment]
Ok, seems nothing too complicated. I will do.

**Comment by x23piracy** [comment]
Thank you so much :)

**Comment by joethefox** [comment]
Done -> https://github.com/joethefox/Unofficial-Official-XBMC-Remote/commit/7134f640f47f5cf336a4175e8a6bd240cfea9a18

Actually it isn't tested, I don't have a pvr setup nearby. If you can, give it a try and report any issue. thank you.

**Comment by x23piracy** [comment]
Could you serve me an ipa?
