### ISSUE TITLE
I could not get the remote to recognise isengard

### ISSUE THREAD

**Issue by AlanApter** [joethefox/Unofficial-Official-XBMC-Remote#59]
I'm running isengard on a fire tv stick, and I cannot get it to find my fire tv stick. HTTP is on, as is zeroconf.

**Comment by joethefox** [comment]
have you tried to enter manually the kodi instance parameters instead of relying on zeroconf? "Find Kodi" at the end is a confort to avoid to enter manually the parameters

**Comment by AlanApter** [comment]
Hi Joe, somehow in the update, 'Allow remote control via http' got turned. I only noticed this while trying to figure out which port to use instead of using zeroconf. Not sure why updating turned it off. Thanks for the help.

**Comment by joethefox** [comment]
you are welcome
